export type ActivityLogViewModel = {
    id: number;
    logName: string;
    description: string;
    event: string;
    subjectType: string;
    subjectId: number;
    causerType: string;
    causerId: number;
    causerName: string;
    properties: Array<any>;
    changes: Array<any>;
    createdAt: string;
    formattedCreatedAt: string;
};
export type AdminViewModel = {
    id: number;
    name: string;
    email: string;
    initials: string;
    createdAt: string;
    updatedAt: string;
    formattedCreatedAt: string;
    formattedUpdatedAt: string;
    roles: Array<any>;
    toArray: Array<any>;
};
export type ApplyFor = 'inventory' | 'craigslist' | 'instagram' | 'facebook_power_pack' | 'google_power_pack';
export type ApplyOn = 'first_image' | 'other_images' | 'last_image';
export type BasicInfoStepViewModel = {
    pipeline: PipelineViewModel;
    companies: { [key: number]: CompanyViewModel };
    frequencies: Array<any>;
    stepper: CreateStepViewModel;
};
export type BrightnessContrast = -100 | 100;
export type BuyersGuideSetting = 'language' | 'print_type' | 'version' | 'pre_print_version' | 'white_print_version' | 'signature_line' | 'coverage';
export type CardsName = 'filters' | 'dashboard' | 'best_selling' | 'average_ages' | 'products_by_age' | 'inventory_health' | 'products_by_price' | 'products_needing_attention';
export type CargoCapacityUnit = 'cu_ft' | 'l';
export type CategoryName = 'cars' | 'boats' | 'motorcycles' | 'trucks' | 'vans' | 'trailers' | 'parts' | 'powersports';
export type ClassifiedPrice = 'default' | 'website' | 'craigslist' | 'fbmp';
export type CompanyViewModel = {
    id: number;
    name: string;
    email: string;
    status: string;
    phone: string;
    address: Array<any>;
    website: string;
    contactPerson: string;
    hasAddedProduct: boolean;
    createdAt: string;
    updatedAt: string;
    toArray: Array<any>;
};
export type CreateStepViewModel = {
    steps: Array<StepViewModel>;
    current: StepViewModel;
};
export type DimensionType = '400x300' | '800x600' | '1024x768' | '1000x750' | '1600x1200';
export type DownloaderConfigStepViewModel = {
    pipeline: PipelineViewModel;
    stepper: CreateStepViewModel;
    downloaderType: string;
    config: any;
    source: string;
    host: string;
    port: number;
    username: string;
    password: string;
    file: string;
    timeout: number;
    retryAttempts: number;
    headers: Array<any>;
    method: string;
    body: string;
    queryParams: Array<any>;
    verifySsl: boolean;
    followRedirects: boolean;
};
export type EquipmentGroup = 'Mechanical' | 'Exterior' | 'Entertainment' | 'Interior' | 'Safety' | 'Optional';
export type FillType = 'auto' | 'blur' | 'color';
export type FilterConfigStepViewModel = {
    pipeline: PipelineViewModel;
    stepper: CreateStepViewModel;
    config: any;
    rules: Array<any>;
    availableOperators: { [key: string]: string };
    testResult: { [key: string]: any } | null;
    feedKeys: Array<any>;
};
export type FilterOperator = '=' | '!=' | '>' | '>=' | '<' | '<=' | 'like' | 'not_like' | 'in' | 'not_in' | 'between' | 'not_between' | 'is_null' | 'is_not_null' | 'starts_with' | 'ends_with' | 'contains';
export type FitType = 'fit-in' | 'full-fit-in' | 'adaptive-fit-in' | 'adaptive-full-fit-in';
export type FormatType = 'webp' | 'jpg' | 'png' | 'gif' | 'avif' | 'heic';
export type FuelUnit = 'mpg' | 'l_100km';
export type ImageDownloadMode = 'all' | 'new_products_only' | 'products_without_images';
export type ImagesPrepareConfigStepViewModel = {
    pipeline: PipelineViewModel;
    stepper: CreateStepViewModel;
    config: any;
    imageIndexesToSkip: Array<any>;
    imageSeparator: string;
    active: boolean;
    downloadMode: string;
};
export type ImportPipelineFrequency = 'once' | 'daily' | 'weekly' | 'monthly';
export type ImportPipelineStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
export type ImportPipelineStep = 'basic-info' | 'downloader-config' | 'reader-config' | 'filter-config' | 'mapper-config' | 'images-prepare-config' | 'prepare-config' | 'preview';
export type ListActivityLogViewModel = {
    logs: any;
    pipeline: PipelineViewModel;
    paginator: PaginatorViewModel;
};
export type ListAdminViewModel = {
    admins: Array<AdminViewModel>;
    paginator: PaginatorViewModel;
};
export type ListPipelineViewModel = {
    pipelines: Array<PipelineViewModel>;
    paginator: PaginatorViewModel;
    stats: PipelineStatsViewModel;
};
export type MapperConfigStepViewModel = {
    pipeline: PipelineViewModel;
    stepper: CreateStepViewModel;
    config: any;
    fieldMappings: Array<any>;
    supportsValueMapping: boolean;
    availableTransformations: Array<any>;
    feedKeys: Array<any>;
    targetFields: Array<any>;
    testResult: Array<any>;
};
export type MileageUnit = 'mi' | 'km' | 'hr';
export type PaginatorViewModel = {
    currentPage: number;
    hasMorePages: boolean;
    lastPage: number;
    perPage: number;
    total: number;
    nextPageUrl: string;
    previousPageUrl: string;
};
export type PerformanceUnit = 'sec';
export type PipelineStage = 'download' | 'read' | 'filter' | 'map' | 'images_prepare' | 'prepare' | 'save';
export type PipelineStatsViewModel = {
    active: number;
    successful: number;
    failed: number;
    running: number;
    total: number;
    successRate: number;
    failureRate: number;
};
export type PipelineStatus = 'active' | 'inactive' | 'needs_configuration';
export type PipelineViewModel = {
    id: number;
    name: string;
    description: string;
    company: CompanyViewModel;
    frequency: string;
    startTime: string;
    formattedStartTime: string;
    isActive: boolean;
    status: Array<any>;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    formattedCreatedAt: string;
    formattedUpdatedAt: string;
    lastExecutedAt: string;
    formattedLastExecutedAt: string;
    nextExecutionAt: string;
    formattedNextExecutionAt: string;
    config: any;
};
export type PreviewStepViewModel = {
    pipeline: PipelineViewModel;
    stepper: CreateStepViewModel;
    hasError: boolean;
    error: string;
    hasResult: boolean;
    result: Array<any>;
    previewData: Array<any>;
    columns: Array<any>;
    stats: Array<any>;
    errors: Array<any>;
};
export type PriceListFields = 'vehicle' | 'fuel_highway' | 'color' | 'engine' | 'condition' | 'body_style' | 'mileage' | 'fuel_city' | 'special_price' | 'asking_price';
export type PriceListPrintFor = 'published' | 'draft' | 'sold';
export type PriceListSorts = 'productable.year' | 'productable.make' | 'created_at' | 'productable.sold_at' | 'price';
export type PriceSetting = 'default' | 'asking' | 'special' | 'classified';
export type PriceValueType = 'price' | 'text' | 'no_price' | 'down_payment' | 'cash';
export type ProductAction = 'publish' | 'pending' | 'draft' | 'sold' | 'reset_age' | 'trash' | 'featured' | 'print_buyer_guide' | 'print_window_sticker' | 'print_price_list' | 'print_kbb' | 'print_nada';
export type ProductStatus = 'published' | 'draft' | 'pending' | 'sold' | 'trash';
export type QRCodeOption = 'customLink' | 'vehicleDetails' | 'dealershipWebsite';
export type QualityType = 'ultra' | 'high' | 'medium' | 'low';
export type ReaderConfigStepViewModel = {
    pipeline: PipelineViewModel;
    stepper: CreateStepViewModel;
    readerType: string;
    config: any;
    delimiter: string;
    enclosure: string;
    escape: string;
    hasHeader: boolean;
    trim: boolean;
    entryPoint: string;
    keepRoot: boolean;
    testResult: Array<any>;
};
export type SectorName = 'vehicles' | 'electronics' | 'real_estate';
export type SharpenLevel = 'level-1' | 'level-2' | 'level-3';
export type StepViewModel = {
    step: ImportPipelineStep;
    route: string;
    isAvailable: boolean;
    index: number;
    title: string;
    description: string;
};
export type TestDataMapperViewModel = {
    fromArray: TestDataMapperViewModel;
    fromMapperResult: TestDataMapperViewModel;
    isSuccess: boolean;
    getMessage: string;
    getDetails: Array<any>;
    testResult: Array<any>;
};
export type TestDownloaderViewModel = {
    fromDownloadResult: TestDownloaderViewModel;
    fromArray: TestDownloaderViewModel;
    testResult: Array<any>;
    isSuccess: boolean;
    getMessage: string;
    getDetails: Array<any>;
    getFormattedResult: Array<any>;
};
export type TestFilterViewModel = {
    fromFilterResult: TestFilterViewModel;
    fromArray: TestFilterViewModel;
    isSuccess: boolean;
    getMessage: string;
    testResult: Array<any>;
    getDetails: Array<any>;
};
export type TestReaderViewModel = {
    fromArray: TestReaderViewModel;
    fromReaderResult: TestReaderViewModel;
    isSuccess: boolean;
    getMessage: string;
    getDetails: Array<any>;
    testResult: Array<any>;
};
export type ToastNotificationVariant = 'destructive' | 'default';
export type VehicleHistoryBadge = 'carfax-bb' | 'carfax-ca' | 'carfax-owner' | 'certified-used' | 'autocheck' | 'carproof';
export type VinDisplayOption = 1 | 0 | 2;
export type WsDescription = 'feature' | 'standardEquipment' | 'description';
