[program:default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/import-pipeline/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600 --memory=1024
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/log/supervisor/default-worker.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=20
stopwaitsecs=3600
