[program:default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:listen --queue=default --timeout=0 --memory=1024
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/log/supervisor/default-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
